version: "3.5"
services:
  app:
    image: django-app
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      app-postgres:
        condition: service_healthy

  app-postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - "app-postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: django-postgres
      POSTGRES_USER: django_admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", '-U', "django_admin"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  app-postgres:
    name: "app-postgres"